---

- name: Update main configuration file
  template:
    src:   'zabbix_proxy.conf.j2'
    dest:  '{{ zabbix_proxy__conf_file }}'
    owner: root
    group: '{{ zabbix_proxy__service_group }}'
    mode:  0640
  notify: [ 'restart-zabbix-proxy' ]
