---
- fail:
    msg: You must fill the proxy type
  when: zabbix_proxy__type is not defined

- name: Assert required variables
  assert:
    that:
      - zabbix_proxy__type in ['mysql', 'pgsql', 'sqlite3']
      - zabbix_proxy__mode in [0, 1]
      - zabbix_proxy__mode == 1 or zabbix_proxy__server is defined
      - 1024 <= zabbix_proxy__server_port and zabbix_proxy__server_port <= 32767
      - 1024 <= zabbix_proxy__listen_port and zabbix_proxy__listen_port <= 32767
      - zabbix_proxy__db_name is defined or zabbix_proxy__type in ['sqlite3']
      - 0 <= zabbix_proxy__log_size and zabbix_proxy__log_size <= 1024
      - 0 <= zabbix_proxy__local_buffer and zabbix_proxy__local_buffer <= 720
      - 1 <= zabbix_proxy__offline_buffer and zabbix_proxy__offline_buffer <= 720
      - 0 <= zabbix_proxy__heartbeat_frequency and zabbix_proxy__heartbeat_frequency <= 3600
      - 1 <= zabbix_proxy__config_frequency and zabbix_proxy__config_frequency <= (3600*24*7)
      - 1 <= zabbix_proxy__data_sender_frequency and zabbix_proxy__data_sender_frequency <= 3600
      - 0 <= zabbix_proxy__start_pollers and zabbix_proxy__start_pollers <= 1000
      - 0 <= zabbix_proxy__start_ipmi_pollers and zabbix_proxy__start_ipmi_pollers <= 1000
      - 0 <= zabbix_proxy__start_pollers_unreachable and zabbix_proxy__start_pollers_unreachable <= 1000
      - 0 <= zabbix_proxy__start_trappers and zabbix_proxy__start_trappers <= 1000
      - 0 <= zabbix_proxy__start_pingers and zabbix_proxy__start_pingers <= 1000
      - 0 <= zabbix_proxy__start_discoverers and zabbix_proxy__start_discoverers <= 250
      - 0 <= zabbix_proxy__start_http_pollers and zabbix_proxy__start_http_pollers <= 1000
      - 0 <= zabbix_proxy__start_java_pollers and zabbix_proxy__start_java_pollers <= 1000
      - zabbix_proxy__start_java_pollers == 0 or ( zabbix_proxy__java_gateway is defined and zabbix_proxy__java_gateway|length > 0 )
      - zabbix_proxy__start_java_pollers == 0 or ( zabbix_proxy__java_gateway_port is defined and 1024 <= zabbix_proxy__java_gateway_port and zabbix_proxy__java_gateway_port <= 32767 )
      - 0 <= zabbix_proxy__start_snmp_trapper and zabbix_proxy__start_snmp_trapper <= 1

- name: Ensure default Sqlite database path
  set_fact:
    zabbix_proxy__db_name: '{{ zabbix_proxy__var_directory }}/proxy_db.sqlite'
  when: zabbix_proxy__type in ['sqlite3'] and zabbix_proxy__db_name is not defined
